const fakeProjects = [
  {
    id: '1',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/1.png').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '2',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/2.jpg').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '3',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/3.jpg').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '4',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/4.png').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '5',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/5.png').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '6',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/6.jpg').default,
    imageBackground: '#0071fe',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '7',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/7.png').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '8',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/8.jpg').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '9',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/9.png').default,
    imageBackground: '#fff',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '10',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/10.png').default,
    imageBackground: '#f7f7f7',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '11',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/11.png').default,
    imageBackground: '#e0234e',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
  {
    id: '12',
    name: 'Project name',
    description:
      'Summary explaning what this project is about and why you should fund. No more than 3 lines to look nice',
    image: require('./images/12.jpg').default,
    imageBackground: '#eed94a',
    total: 23991,
    match: 17128,
    donors: 292,
    avatars: [
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
      require('./avatars/avatar-dog.jpg').default,
    ],
  },
];

export default fakeProjects;
