FROM node:15.1.0-alpine3.12

#   Install updates and required packages
RUN apk update \
&&  apk upgrade \
&&  apk add \
        docker-cli \
        git \
        make \
        cmake \
        bash \
        python3 \
        g++
